apiVersion: v1
kind: Secret
metadata:
  name: podchef-backend-secret
stringData:
  API_DB_USER: "<username here>"
  API_DB_PASSWORD: "<password here>"
  API_TOKEN_SECRET: "<secret here>"
  API_EMAIL_HOST: "<email protocol here>"
  API_EMAIL_PORT: "<email port here>"
  API_EMAIL_FROM: "<email sender here>"
  API_EMAIL_PASSWORD: "<email password>"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - name: api
        image: podchef/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1323
        envFrom:
        - secretRef:
            name: podchef-backend-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: api
  name: api
  annotations:
    haproxy.org/check: "enabled"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
spec:
  selector:
    run: api
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    targetPort: 1323

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
spec:
  rules:
  - host: "api"
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: api
            port: 
              number: 80